---
# users: Tasks entry point. Called by main.yml 

- name: add {{ ansible_client_user }} user
  user: >
        name={{ ansible_client_user }}
        uid={{users[ansible_client_user]['uid']}}
        home={{users[ansible_client_user]['home']}}
        state=present

- name: make sure {{ ansible_client_user }} has sudo access
  lineinfile: >
              dest=/etc/sudoers
              validate='/usr/sbin/visudo -cf %s'
              regexp="^{{ ansible_client_user }}\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$"
              line="{{ ansible_client_user }} ALL=(ALL)      NOPASSWD: ALL"
              state=present

- name: install {{ ansible_client_user }} public key
  authorized_key: >
                  user={{ ansible_client_user }}
                  key="{{ item }}"
                  state=present
  with_file:
    - "{{users[ansible_client_user]['home']}}/.ssh/id_rsa.pub"
