---
# users: Tasks entry point. Called by main.yml 

###- name: adding cfm
###  user:
###    name: cfm
###    home: /usr/local/cfm
###    shell: /bin/bash
###
###- name: adding cfm key
###  authorized_key:
###    user: cfm
###    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
###
- name: Add {{ ansible_client_group }} group
  group: >
         name={{ ansible_client_group }}
         gid={{ groups[ansible_client_group]['gid'] }}
         state=present

- name: Add {{ ansible_client_user }} user
  user: >
        name={{ ansible_client_user }}
        uid={{users[ansible_client_user]['uid']}}
        group={{ ansible_client_group }}
        home={{users[ansible_client_user]['home']}}
        state=present

- name: Make sure {{ ansible_client_user }} has sudo access
  lineinfile: >
              dest=/etc/sudoers
              validate='/usr/sbin/visudo -cf %s'
              regexp="^{{ ansible_client_user }}\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL$"
              line="{{ ansible_client_user }} ALL=(ALL)      NOPASSWD: ALL"
              state=present
