- name: example playbook
  hosts: jenkins 
  gather_facts: yes
  user: root

  pre_tasks:
#   - name: install packages
#     yum: 
#        name={{ item }}
#        state=present
#        update_cache=yes
#     with_items:
#       - vim
#       - mc
#       - net-tools
#       - less
#       - tmux

  roles:
   - role: dns
   - role: base-linux
   - role: users
