---
# docker: Tasks entry point. Called by main.yml 
- name: add docker repo
  yum_repository:
    name: docker
    description: docker repo
    file: docker
    baseurl: https://yum.dockerproject.org/repo/testing/centos/$releasever/
    enabled: yes
    state: present
    gpgcheck: no

- name: install docker engine
  yum:
    name: "docker-engine"
    state: present
    disable_gpg_check: yes

- name: enable docker engine
  service:
    name: docker
    state: started
    enabled: yes
